Ts range fix
THUIGinX/IGinX pull request #8
Opened 2023-02-04 16:24 UTC by RemHero

2023-02-07 01:16 UTC, zhuyuqing approved these changes
LGTM

2023-02-08 01:27 UTC, iznauy requested changes

2023-02-08 02:09 UTC, RemHero commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
> +        String regEx = "[~!@#$%&()+=|{}':;',<>?~]|\r|\n|\t|[\u2E80-\u2E84]";
tagkv的前后特殊中文字符，详见TagKVUtils中，以及rest-annotation使用的特殊字符

2023-02-09 01:01 UTC, Cauchy-NY approved these changes

2023-02-09 02:45 UTC, iznauy approved these changes

2023-02-09 03:20 UTC, merged